version: "3.8"

services:
  mysql:
    build:
      context: ./blog-database
      dockerfile: ./docker/Dockerfile
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - /home/data:/var/lib/mysql
    # environment:
    #   - "MYSQL_ROOT_PASSWORD=123456"
    #   - "ADMIN_USER_NAME=admin"
    #   - "ADMIN_USER_PASSWORD=admin"
    ports:
      - "3306:3306"

  eggjs:
    build:
      context: ./blog-server
      dockerfile: ./docker/Dockerfile
    image: eggjs:latest
    container_name: eggjs
    restart: always
    ports:
      - "7001:7001"
    depends_on:
      - mysql

  admin:
    build:
      context: ./blog-admin
      dockerfile: ./docker/Dockerfile
    image: admin:latest
    container_name: admin
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - eggjs

  blog:
    build:
      context: ./blog
      dockerfile: ./docker/Dockerfile
    image: blog:latest
    container_name: blog
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - eggjs
