version: "3.8"

services:
  mysql:
    build:
      context: ./blog-database
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"

  eggjs:
    build:
      context: ./blog-server
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "7001:7001"
    depends_on:
      - mysql

  admin:
    build:
      context: ./blog-admin
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - eggjs

  blog:
    build:
      context: ./blog
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - eggjs
